AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    Description: Enter t2.micro. Default is t2.micro.
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
Resources:
  razanBucket:
    Type: AWS::S3::Bucket
  RazanQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 30
  RazanEc2:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceTypeParameter
