AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    Description: Enter t2.micro. Default is t2.micro.
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
Resources:
  razanBucket:
    Type: AWS::S3::Bucket
  RazanQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 30
  RazanEc2:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceTypeParameter
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - "subnet-05dc5323a90701745"

        - "subnet-0462080141c44392d"

        - "subnet-0441c0b1c024fa494"

        - "subnet-0e8cecdb378d728af"

        - "subnet-0e2ac274cda7f0de0"

        - "subnet-011535b5492b30052"
      Tags:
        - Key: Name
          Value: RazanALB
Outputs:
  MyLoadBalancerDNSName:
    Description: The DNSName of the backup load balancer
    Value: !GetAtt MyLoadBalancer.DNSName
